@startuml
'https://plantuml.com/activity-diagram-beta
partition ConnectPyCharmWithGitHub {
    start
    :Sign In to GitHub;
    :GOTO: Create a new repository;
    :FILL DATA FIELD: "Repository name";
    :FILL DATA FIELD: "Description";
    :CHOOSE: Public or Private;
    :PRESS: Create repository;
    if (idk)
        :FIND: SSH;
        :PESS: SSH;
        :COPY: Link right next to SSH;
        :GOTO: PyCharm;
        :GOTO: GIt;
        :PRESS: Clone;
        :FILL DATA FIELD: "URL" WITH: Link right next to SSH;
        :PRESS Clone;
    else
        :FIND: HTTPS;
        :PESS: HTTPS;
        :COPY: Link right next to HTTPS;
        :GOTO: PyCharm;
        :RIGHT CLICK ON: Project's folder;
        :GOTO: "Git";
        :PRESS: "Manage remotes";
        :PRESS: "Add";
        :"FILL DATA FIELD: "URL" WITH: Link right next to HTTPS;
        :FILL DATA FIELD: "Name" WITH: ...;
    endif
stop
}
partition AddFileToStagingArea {
    start
    :CREATE: File with "README" name and ".md" extension;
    if (Choice exists to add "README" to Git)
        :Add "README" to Git;
    else
        :RIGHT CLICK ON: "README.md";
        :GOTO: "Git";
        :PRESS: "Add";
    endif
stop
}

partition CommitAllChangedFiles {
start
    :GOTO: PyCharm;
    :PRESS: Commit;
    :MARK: Square left to "Changes <number> files";
    :FILL DATA FIELD: "Black quare in Commit" WITH: "Information related to the Changes";
    :PRESS: "Commit";
stop
}

partition PushStagedFiles {
start
    :GOTO: PyCharm;
    :PRESS: Push;
    :CHOOSE AND PRESS: Commit needed to be pushed;
    :PRESS: Push;
stop
}

partition AddToGitignore {
start
    :ASSUMPTION:;
    :CREATE: File with name <name> and extension <extension>;
    :RIGHT CLICK ON: File created last time;
    :GOTO: Git;
    :GOTO: "Add to .gitignore";
    :"PRESS: ".gitignore";
    if (.gitignore is not created and appropriate window popped up)
        :PRESS: "Add";
    endif
stop
}

partition CreateBranchFromMaster {
    :GOTO: PyCharm;
    :PRESS: Git;
    :DROP DOWN: Local;
    :RIGHT CLICK: master;
    :PRESS: "New branch from 'master'...";
    :FILL DATA FIELD: "New branch name:" WITH: <branch name>;
    stop
}

partition PushNewBranchToGitHub{
    start
    :GOTO: PyCharm;
    :PRESS: "Git";
    :RIGHT CLICK ON: New branch to push;
    :PRESS: "checkout";
    :CALL: PushStagedFiles;
    stop
}
partition UpdateLocalRepository{
    start
    :GOTO: PyCharm;
    :PRESS: "Updare project...";
    :PRESS: OK;
    stop
}
@enduml
